import { useState } from "react";

export default function AdminReviewActions({ status, busy, feedback, onFeedback, onAction }) {
  const [confirming, setConfirming] = useState("");
  if (status === "SUBMITTED") return <section className="admin-actions" aria-labelledby="actions-title"><h2 id="actions-title">Acciones de revisión</h2><button className="futura-primary" type="button" disabled={busy} onClick={() => onAction("start")}>{busy ? "Procesando…" : "Iniciar revisión"}</button></section>;
  if (status !== "IN_REVIEW") return null;
  const decide = (action) => { if (action === "changes") { onAction(action); return; } setConfirming(action); };
  return <section className="admin-actions" aria-labelledby="actions-title"><h2 id="actions-title">Decisión de revisión</h2><label htmlFor="admin-feedback">Feedback para el estudiante</label><textarea id="admin-feedback" value={feedback} onChange={(event) => onFeedback(event.target.value)} disabled={busy} rows="5" maxLength="4000"/><div className="admin-action-buttons"><button type="button" disabled={busy || !feedback.trim()} onClick={() => decide("changes")}>Solicitar cambios</button><button className="danger-action" type="button" disabled={busy || !feedback.trim()} onClick={() => decide("reject")}>Rechazar</button><button className="futura-primary" type="button" disabled={busy} onClick={() => decide("approve")}>Aprobar</button></div>{confirming && <div className="admin-confirm" role="alertdialog" aria-modal="true" aria-labelledby="confirm-title"><h3 id="confirm-title">{confirming === "approve" ? "¿Aprobar este proyecto?" : "¿Rechazar este proyecto?"}</h3><p>{confirming === "approve" ? "El backend actualizará el progreso de la zona." : "La participación quedará abandonada y no sumará progreso."}</p><div><button type="button" disabled={busy} onClick={() => setConfirming("")}>Cancelar</button><button className={confirming === "reject" ? "danger-action" : "futura-primary"} type="button" disabled={busy} onClick={() => { const action = confirming; setConfirming(""); onAction(action); }}>{busy ? "Procesando…" : "Confirmar"}</button></div></div>}</section>;
}
