import { useCallback, useEffect, useState } from "react";
import { Link, useLocation, useNavigate, useParams } from "react-router-dom";
import { approveContribution, getAdminContribution, rejectContribution, requestChanges, startReview } from "../api/impactAdminApi";
import AdminAuditTimeline from "../components/futura/AdminAuditTimeline";
import AdminReviewActions from "../components/futura/AdminReviewActions";
import { FuturaHeader, PageState } from "../components/futura/FuturaUi";
import ProjectStatus from "../components/futura/ProjectStatus";

const formatDate = (value) => value ? new Intl.DateTimeFormat("es-MX", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—";
const safeLink = (value) => { try { const url = new URL(value); return ["http:", "https:"].includes(url.protocol) ? url.href : null; } catch { return null; } };

export default function FuturaAdminContributionPage() {
  const { contributionId } = useParams(); const navigate = useNavigate(); const location = useLocation(); const [item, setItem] = useState(null); const [status, setStatus] = useState("loading"); const [busy, setBusy] = useState(false); const [feedback, setFeedback] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const load = useCallback(async (showLoading = true) => { if (showLoading) setStatus("loading"); try { const next = await getAdminContribution(contributionId); setItem(next); setStatus("ready"); return next; } catch (requestError) { if (requestError.response?.status === 401) { navigate(`/login?from=${encodeURIComponent(location.pathname)}`, { replace: true }); return null; } setStatus(requestError.response?.status === 403 ? "forbidden" : requestError.response?.status === 404 ? "missing" : "error"); return null; } }, [contributionId, location.pathname, navigate]);
  useEffect(() => { load(); }, [load]);
  const act = async (action) => { if (busy) return; if (["changes", "reject"].includes(action) && !feedback.trim()) { setError("Escribe feedback antes de continuar."); return; } setBusy(true); setError(""); setMessage(""); try { let next; if (action === "start") next = await startReview(item.id, item.revision); if (action === "changes") next = await requestChanges(item.id, item.revision, feedback.trim()); if (action === "reject") next = await rejectContribution(item.id, item.revision, feedback.trim()); if (action === "approve") next = await approveContribution(item.id, item.revision, feedback.trim()); setItem(next); if (["changes", "reject", "approve"].includes(action)) setFeedback(""); setMessage(action === "approve" ? "Proyecto aprobado. El progreso de la zona fue actualizado." : action === "reject" ? "Proyecto rechazado." : action === "changes" ? "Cambios solicitados al estudiante." : "Revisión iniciada."); } catch (requestError) { if (requestError.response?.status === 409) { setError("Esta revisión cambió desde que la abriste. Cargamos la versión más reciente."); await load(false); } else if (requestError.response?.status === 400) setError(requestError.response?.data?.message || "Revisa los datos de la decisión."); else if (requestError.response?.status === 401) navigate(`/login?from=${encodeURIComponent(location.pathname)}`, { replace: true }); else if (requestError.response?.status === 403) setStatus("forbidden"); else if (requestError.response?.status === 404) setStatus("missing"); else setError("No pudimos completar la acción. Tu feedback permanece disponible."); } finally { setBusy(false); } };
  if (status === "loading") return <PageState title="Cargando entrega"><p>Consultando la versión más reciente.</p></PageState>;
  if (status === "forbidden") return <PageState title="Acceso restringido"><p>Tu cuenta no tiene permisos para revisar esta contribución.</p></PageState>;
  if (status === "missing") return <PageState title="Entrega no encontrada"><p>La contribución no existe o ya no está disponible.</p></PageState>;
  if (status === "error") return <PageState title="No pudimos cargar la entrega" onRetry={load}><p>Intenta nuevamente en un momento.</p></PageState>;
  const mission = item.participation?.mission; const author = item.participation?.user; const resultUrl = safeLink(item.resultUrl); const repositoryUrl = safeLink(item.repositoryUrl);
  return <main className="futura-page"><FuturaHeader/><article className="admin-detail"><header><Link to="/admin/futura">← Bandeja de entregas</Link><p className="eyebrow">{mission?.zone?.name || "Distrito Cero"}</p><h1>{item.title || "Contribución sin título"}</h1><div className="project-statuses"><ProjectStatus value={item.status}/><ProjectStatus value={item.participation?.status}/></div></header><div className="admin-detail-grid"><section className="admin-submission" aria-labelledby="submission-title"><h2 id="submission-title">Entrega del estudiante</h2><dl className="admin-metadata"><div><dt>Autor</dt><dd>{author?.name || "Sin nombre"} · {author?.email || "Sin email"}</dd></div><div><dt>Misión</dt><dd>{mission?.title || "—"}</dd></div><div><dt>Revisión</dt><dd>{item.revision}</dd></div><div><dt>Enviada</dt><dd>{formatDate(item.submittedAt)}</dd></div><div><dt>Revisada</dt><dd>{formatDate(item.reviewedAt)}</dd></div></dl>{item.reviewerFeedback && <aside className="review-feedback"><h2>Feedback actual</h2><p>{item.reviewerFeedback}</p></aside>}{[["Descripción", item.description],["Notas del proceso", item.processNotes],["Reflexión", item.reflection]].map(([label,value]) => value && <section className="submission-field" key={label}><h3>{label}</h3><p>{value}</p></section>)}{(resultUrl || repositoryUrl) && <div className="project-links">{resultUrl && <a href={resultUrl} target="_blank" rel="noopener noreferrer">Ver resultado ↗</a>}{repositoryUrl && <a href={repositoryUrl} target="_blank" rel="noopener noreferrer">Ver repositorio ↗</a>}</div>}<section className="submission-field"><h3>Capacidades de la misión</h3><div className="capability-list">{(mission?.capabilities || []).map((link) => <span key={link.capability?.id || link.id}>{link.capability?.name || link.name}</span>)}</div>{!mission?.capabilities?.length && <p>No hay capacidades asociadas.</p>}</section></section><aside className="admin-review-panel"><AdminReviewActions status={item.status} busy={busy} feedback={feedback} onFeedback={setFeedback} onAction={act}/><div className="project-message" aria-live="polite">{error && <p className="futura-error">{error}</p>}{message && <p className="futura-success">{message}</p>}</div>{item.status === "APPROVED" && mission?.zone?.slug && <Link className="futura-primary" to={`/futura/zones/${encodeURIComponent(mission.zone.slug)}`}>Ver zona</Link>}<AdminAuditTimeline events={item.auditEvents}/></aside></div></article></main>;
}
