import { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { getImpactMissions, getImpactZones } from "../api/impactApi";
import DistrictScene, { ZonePanel } from "../components/futura/DistrictScene";
import { FuturaHeader, PageState, Progress } from "../components/futura/FuturaUi";

export default function FuturaDistrictPage() {
  const [zones, setZones] = useState([]); const [activeSlug, setActiveSlug] = useState(""); const [status, setStatus] = useState("loading");
  const load = useCallback(async () => { setStatus("loading"); try { const [zoneData, missionData] = await Promise.all([getImpactZones(), getImpactMissions()]); const items = Array.isArray(zoneData) ? zoneData : []; const missions = Array.isArray(missionData) ? missionData : []; const enriched = items.map((zone) => ({ ...zone, missionCount: missions.filter((mission) => mission.zone?.id === zone.id || mission.zone?.slug === zone.slug).length })); setZones(enriched); setActiveSlug((current) => current || enriched[0]?.slug || ""); setStatus("ready"); } catch { setStatus("error"); } }, []);
  useEffect(() => { load(); }, [load]);
  if (status === "loading") return <PageState title="Reconstruyendo el mapa"><p>Consultando el estado real de Distrito Cero…</p></PageState>;
  if (status === "error") return <PageState title="El distrito no está disponible" onRetry={load}><p>No pudimos consultar las zonas. Intenta nuevamente.</p></PageState>;
  const activeZone = zones.find((zone) => zone.slug === activeSlug) || zones[0];
  return <main className="futura-page"><FuturaHeader/><section className="futura-hero"><div><p className="eyebrow">FUTURA · Distrito Cero</p><h1>No elijas primero una carrera. Elige algo que merezca ser cambiado.</h1><p>Explora problemas, participa en proyectos y descubre capacidades a partir de experiencias reales.</p></div><div className="futura-hero-mark" aria-hidden="true">04<small>zonas en recuperación</small></div></section><section className="district-layout" aria-labelledby="district-title"><div><div className="futura-section-heading"><div><p className="eyebrow">Mapa público</p><h2 id="district-title">Un distrito que cambia con acciones reales</h2></div><p>Selecciona un edificio para explorar sus misiones.</p></div><DistrictScene zones={zones} activeSlug={activeSlug} onActive={setActiveSlug}/></div><ZonePanel zone={activeZone}/></section><section className="zone-list" aria-labelledby="zones-list-title"><div className="futura-section-heading"><div><p className="eyebrow">Alternativa accesible</p><h2 id="zones-list-title">Todas las zonas</h2></div></div><div className="zone-card-grid">{zones.map((zone) => <article key={zone.id || zone.slug} className="zone-card"><h3>{zone.name}</h3><p>{zone.description}</p><Progress zone={zone}/><Link to={`/futura/zones/${encodeURIComponent(zone.slug)}`}>Ver zona <span aria-hidden="true">→</span></Link></article>)}</div>{zones.length === 0 && <p className="futura-empty">No hay zonas publicadas por ahora.</p>}</section><section className="futura-how"><p className="eyebrow">Cómo funciona</p><h2>Explora, crea evidencia y transforma el distrito.</h2><ol><li><strong>Explora</strong><span>Conoce una necesidad y elige una misión.</span></li><li><strong>Construye</strong><span>Documenta una solución segura y verificable.</span></li><li><strong>Transforma</strong><span>Las contribuciones aprobadas activan progreso real.</span></li></ol></section></main>;
}
