import { useCallback, useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { getMyCareerOptions, getMyFootprint } from "../api/impactApi";
import { FuturaHeader, PageState } from "../components/futura/FuturaUi";

const dateFormatter = new Intl.DateTimeFormat("es-MX", { dateStyle: "long" });
const evidenceLabel = (count) => `${count} ${count === 1 ? "evidencia" : "evidencias"}`;
const academicLevelLabel = (level) => ({ tsu: "Técnico Superior Universitario", licenciatura: "Licenciatura", ingenieria: "Ingeniería" }[level] || level);
const normalizeIdentity = (value) => String(value || "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toUpperCase().trim();

function groupInstitutions(careerOptions) {
  const groups = new Map();
  careerOptions.forEach((option) => option.offerings.forEach((offering) => {
    const key = `${normalizeIdentity(offering.institutionName)}|${normalizeIdentity(offering.municipality)}`;
    if (!groups.has(key)) groups.set(key, { institutionName: offering.institutionName, institutionShortName: offering.institutionShortName, municipality: offering.municipality, programs: [], campuses: new Map() });
    const group = groups.get(key);
    const programIdentity = `${option.canonicalProgramKey}|${offering.educativeOfferId}|${offering.campusId}|${offering.redirectUrl}`;
    if (!group.programs.some((program) => program.identity === programIdentity)) group.programs.push({ identity: programIdentity, canonicalProgramKey: option.canonicalProgramKey, programName: option.programName, offeredProgramName: offering.offeredProgramName, campusId: offering.campusId, campusName: offering.campusName, redirectUrl: offering.redirectUrl });
    const campusIdentity = normalizeIdentity(offering.campusName) || offering.campusId;
    if (campusIdentity && !group.campuses.has(campusIdentity)) group.campuses.set(campusIdentity, { id: offering.campusId, name: offering.campusName });
  }));
  return [...groups.values()].map((group) => ({ ...group, campuses: [...group.campuses.values()] }));
}

function CapabilitySection({ capabilities }) {
  return <section className="footprint-section" aria-labelledby="footprint-capabilities"><div className="footprint-section-heading"><p className="eyebrow">Evidencia verificada</p><h2 id="footprint-capabilities">Capacidades demostradas</h2><p>Estas capacidades aparecen porque las pusiste en práctica en proyectos aprobados.</p></div><div className="footprint-capability-list">{capabilities.map((capability) => <article className="footprint-capability" key={capability.id}><header><div><span>{capability.category}</span><h3>{capability.name}</h3></div><strong>{evidenceLabel(capability.evidenceCount)}</strong></header>{capability.description && <p>{capability.description}</p>}<details><summary>Ver evidencias</summary><ul>{capability.evidence.map((evidence) => <li key={`${capability.id}-${evidence.contributionId}`}><div><strong>{evidence.contributionTitle}</strong><span>{evidence.missionTitle}</span></div><small>{evidence.zoneName} · {dateFormatter.format(new Date(evidence.approvedAt))}</small></li>)}</ul></details></article>)}</div></section>;
}

function CareerSection({ data, status, onRetry }) {
  if (status === "loading") return <section className="footprint-section footprint-careers" aria-labelledby="footprint-careers"><div className="footprint-section-heading"><p className="eyebrow">Disponibilidad educativa</p><h2 id="footprint-careers">Carreras e instituciones relacionadas</h2></div><div className="footprint-inline-state" role="status">Buscando ofertas educativas activas…</div></section>;
  if (status === "error") return <section className="footprint-section footprint-careers" aria-labelledby="footprint-careers"><div className="footprint-section-heading"><p className="eyebrow">Disponibilidad educativa</p><h2 id="footprint-careers">Carreras e instituciones relacionadas</h2></div><div className="footprint-inline-state is-error" role="alert"><p>No pudimos cargar las opciones educativas. Tu Huella sigue disponible.</p><button type="button" onClick={onRetry}>Reintentar opciones</button></div></section>;
  const options = data?.careerOptions || [];
  const institutions = groupInstitutions(options);
  return <section className="footprint-section footprint-careers" aria-labelledby="footprint-careers"><div className="footprint-section-heading"><p className="eyebrow">Conexiones verificables</p><h2 id="footprint-careers">Carreras relacionadas con tu Huella</h2><p>Estas carreras están relacionadas con las capacidades que demostraste. El orden proviene del análisis backend de tu evidencia aprobada.</p></div>{options.length === 0 ? <div className="footprint-inline-state"><h3>Aún no hay ofertas navegables</h3><p>Aún no encontramos ofertas educativas activas y navegables relacionadas con esta Huella. Tus capacidades siguen siendo válidas.</p><Link to="/futura">Seguir explorando proyectos</Link></div> : <><div className="footprint-career-list">{options.map((option) => { const names = option.matchedCapabilities.map((capability) => capability.name); return <article className="footprint-career" key={option.canonicalProgramKey}><div><span>{academicLevelLabel(option.academicLevel)}</span><h3>{option.programName}</h3><p>Relacionado porque demostraste {new Intl.ListFormat("es-MX", { style: "long", type: "conjunction" }).format(names)}.</p><small>Estas capacidades aparecen en {evidenceLabel(option.approvedEvidenceCount)} de proyectos aprobados.</small></div><ul aria-label={`Capacidades relacionadas con ${option.programName}`}>{option.matchedCapabilities.map((capability) => <li key={capability.id}>{capability.name} · {evidenceLabel(capability.evidenceCount)}</li>)}</ul></article>; })}</div>{data.summary.matchedPrograms > data.summary.availablePrograms && <p className="footprint-availability-note">Algunas carreras relacionadas no tienen actualmente una oferta navegable disponible.</p>}<div className="footprint-section-heading institution-heading"><p className="eyebrow">Oferta educativa real</p><h2>Instituciones disponibles</h2><p>Programas, campus y enlaces vigentes asociados a las carreras anteriores.</p></div><div className="institution-list">{institutions.map((institution) => <article className="institution-card" key={`${normalizeIdentity(institution.institutionName)}|${normalizeIdentity(institution.municipality)}`}><header><div><span>{institution.institutionShortName}</span><h3>{institution.institutionName}</h3></div><p>{institution.municipality || "Municipio no especificado"}</p></header>{institution.campuses.length > 0 && <div><h4>Campus</h4><ul>{institution.campuses.map((campus) => <li key={campus.id}>{campus.name || "Campus no especificado"}</li>)}</ul></div>}<div><h4>Programas relacionados</h4><ul className="institution-programs">{institution.programs.map((program) => <li key={program.identity}><div><strong>{program.offeredProgramName || program.programName}</strong>{program.campusName && <small>{program.campusName}</small>}</div><a href={program.redirectUrl} target="_blank" rel="noopener noreferrer">Ver oferta <span aria-hidden="true">↗</span></a></li>)}</ul></div></article>)}</div></>}</section>;
}

export default function FuturaFootprintPage() {
  const [footprint, setFootprint] = useState(null); const [footprintStatus, setFootprintStatus] = useState("loading");
  const [options, setOptions] = useState(null); const [optionsStatus, setOptionsStatus] = useState("loading");
  const loadFootprint = useCallback(async () => { setFootprintStatus("loading"); try { setFootprint(await getMyFootprint()); setFootprintStatus("ready"); } catch { setFootprintStatus("error"); } }, []);
  const loadOptions = useCallback(async () => { setOptionsStatus("loading"); try { setOptions(await getMyCareerOptions()); setOptionsStatus("ready"); } catch { setOptionsStatus("error"); } }, []);
  useEffect(() => { void Promise.allSettled([loadFootprint(), loadOptions()]); }, [loadFootprint, loadOptions]);
  const summary = useMemo(() => footprint?.summary || { approvedProjects: 0, demonstratedCapabilities: 0, evidenceItems: 0 }, [footprint]);
  if (footprintStatus === "loading") return <PageState title="Construyendo tu Huella"><p>Estamos reuniendo tus proyectos aprobados y sus evidencias.</p></PageState>;
  if (footprintStatus === "error") return <PageState title="No pudimos cargar tu Huella" onRetry={loadFootprint}><p>Intenta nuevamente. Tus proyectos no se modificaron.</p></PageState>;
  return <main className="futura-page"><FuturaHeader/><div className="footprint-page"><header className="footprint-hero"><p className="eyebrow">Tu recorrido verificable</p><h1>Mi Huella</h1><p>Tu Huella se construye a partir de proyectos aprobados mediante revisión humana. Las capacidades que aparecen aquí fueron puestas en práctica y verificadas en tus proyectos.</p><nav aria-label="Acciones de Mi Huella"><Link to="/futura/my-projects">Mis proyectos</Link><Link to="/futura">Explorar misiones</Link></nav></header><section className="footprint-summary" aria-label="Resumen de Mi Huella"><article><strong>{summary.approvedProjects}</strong><span>Proyectos aprobados</span></article><article><strong>{summary.demonstratedCapabilities}</strong><span>Capacidades demostradas</span></article><article><strong>{summary.evidenceItems}</strong><span>Evidencias verificadas</span></article></section>{summary.approvedProjects === 0 ? <section className="footprint-empty"><span aria-hidden="true">◇</span><h2>Tu Huella está por comenzar</h2><p>Tu Huella comenzará a construirse cuando uno de tus proyectos sea aprobado.</p><div><Link className="futura-primary" to="/futura">Explorar misiones</Link><Link to="/futura/my-projects">Mis proyectos</Link></div></section> : <><CapabilitySection capabilities={footprint.capabilities}/><CareerSection data={options} status={optionsStatus} onRetry={loadOptions}/></>}</div></main>;
}
