import { useCallback, useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { getMyParticipation, saveContribution, submitContribution } from "../api/impactApi";
import ContributionForm from "../components/futura/ContributionForm";
import { FuturaHeader, PageState } from "../components/futura/FuturaUi";
import ProjectStatus from "../components/futura/ProjectStatus";

const emptyForm = { title: "", description: "", processNotes: "", resultUrl: "", repositoryUrl: "", reflection: "" };
const editableStatuses = new Set(["DRAFT", "IN_PROGRESS", "CHANGES_REQUESTED"]);
const toForm = (contribution) => Object.fromEntries(Object.keys(emptyForm).map((key) => [key, contribution?.[key] || ""]));
const safeLink = (value) => { try { const url = new URL(value); return ["http:", "https:"].includes(url.protocol) ? url.href : null; } catch { return null; } };

export default function FuturaProjectPage() {
  const { participationId } = useParams(); const [project, setProject] = useState(null); const [form, setForm] = useState(emptyForm); const [status, setStatus] = useState("loading"); const [action, setAction] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const load = useCallback(async (showLoading = true) => { if (showLoading) setStatus("loading"); try { const next = await getMyParticipation(participationId); setProject(next); setForm(toForm(next.contribution)); setStatus("ready"); return next; } catch (requestError) { setStatus(requestError.response?.status === 404 ? "missing" : "error"); return null; } }, [participationId]);
  useEffect(() => { load(); }, [load]);
  const stale = async () => { setError("El proyecto cambió en otra sesión. Recargamos la versión más reciente; revisa los datos antes de continuar."); await load(false); };
  const save = async () => { setAction("save"); setError(""); setMessage(""); try { const payload = { ...form }; if (project.contribution) payload.revision = project.contribution.revision; const contribution = await saveContribution(project.id, payload); setProject((current) => ({ ...current, contribution })); setForm(toForm(contribution)); setMessage("Borrador guardado."); return contribution; } catch (requestError) { if (requestError.response?.status === 409) await stale(); else setError("No pudimos guardar. Tus cambios siguen visibles para que puedas intentarlo de nuevo."); return null; } finally { setAction(""); } };
  const submit = async () => { if (!form.title.trim() || ![form.description, form.processNotes, form.resultUrl, form.repositoryUrl].some((value) => value.trim())) { setError("Agrega un título y al menos una evidencia o descripción antes de enviar."); return; } setAction("submit"); setError(""); setMessage(""); try { const payload = { ...form }; if (project.contribution) payload.revision = project.contribution.revision; const saved = await saveContribution(project.id, payload); const contribution = await submitContribution(saved.id, saved.revision); setProject((current) => ({ ...current, contribution })); setForm(toForm(contribution)); setMessage("Contribución enviada a revisión."); } catch (requestError) { if (requestError.response?.status === 409) await stale(); else setError("No pudimos enviar la contribución. El borrador permanece disponible."); } finally { setAction(""); } };
  if (status === "loading") return <PageState title="Abriendo tu proyecto"><p>Cargando la contribución más reciente.</p></PageState>;
  if (status === "missing") return <PageState title="Proyecto no encontrado"><p>No existe o no pertenece a tu cuenta.</p></PageState>;
  if (status === "error") return <PageState title="No pudimos abrir el proyecto" onRetry={load}><p>Intenta nuevamente en un momento.</p></PageState>;
  const contribution = project.contribution; const editable = !contribution || editableStatuses.has(contribution.status); const feedback = contribution?.reviewerFeedback; const resultLink = safeLink(contribution?.resultUrl); const repositoryLink = safeLink(contribution?.repositoryUrl);
  return <main className="futura-page"><FuturaHeader/><article className="project-detail"><header><Link to="/futura/my-projects">← Mis proyectos</Link><p className="eyebrow">{project.mission?.zone?.name || "Distrito Cero"}</p><h1>{project.mission?.title || "Proyecto FUTURA"}</h1><div className="project-statuses"><ProjectStatus value={project.status}/><ProjectStatus value={contribution?.status}/></div></header>{feedback && <section className="review-feedback"><h2>Comentarios de revisión</h2><p>{feedback}</p></section>}<section className="project-editor"><div><h2>{editable ? "Tu contribución" : "Contribución enviada"}</h2><p>{editable ? "Guarda cuando quieras. Al enviar, quedará bloqueada durante la revisión." : "Esta versión es de solo lectura mientras conserva este estado."}</p></div><ContributionForm value={form} onChange={(event) => setForm((current) => ({ ...current, [event.target.name]: event.target.value }))} disabled={!editable || Boolean(action)}/>{!editable && (resultLink || repositoryLink) && <div className="project-links">{resultLink && <a href={resultLink} target="_blank" rel="noopener noreferrer">Ver resultado ↗</a>}{repositoryLink && <a href={repositoryLink} target="_blank" rel="noopener noreferrer">Ver repositorio ↗</a>}</div>}<div className="project-message" aria-live="polite">{error && <p className="futura-error">{error}</p>}{message && <p className="futura-success">{message}</p>}</div>{editable && <footer className="project-actions"><button className="secondary-action" type="button" onClick={save} disabled={Boolean(action)}>{action === "save" ? "Guardando…" : "Guardar borrador"}</button><button className="futura-primary" type="button" onClick={submit} disabled={Boolean(action)}>{action === "submit" ? "Enviando…" : "Guardar y enviar"}</button></footer>}</section></article></main>;
}
